### ISSUE TITLE
Overwrite  scss variables doesn't work

### ISSUE THREAD

**Issue by futbolsalas15** [sweetalert2/ngx-sweetalert2#118] opened 2019-03-26 15:35 UTC
When I try to overwrite the SCSS variables for the _sweetalert2.scss_ file, it doesn't work.

I have my .scss file in this way:

```scss
$swal2-confirm-button-background-color: #a12125; // like red color
@import '~sweetalert2/src/sweetalert2';
```

I have the module config in this way:

```ts
@NgModule({
  imports: [
    CommonModule,
    SweetAlert2Module.forRoot({
      buttonsStyling: false //even without this, it doesn't work 😔
    })
  ],
  declarations: [PopupComponent],
  entryComponents: [PopupComponent]
})
```

And the component (HTML):

```html
<swal
  #swalDialog
  title="{{ title }}"
  text="{{ text }}"
  type="question"
  [showCancelButton]="true"
  [focusCancel]="true"
  (confirm)="confirmButtonClicked()"
>
</swal>
```
However the Sweetalert is showed without changes in the colors:

![error-scss](https://user-images.githubusercontent.com/1960482/55010581-6fcd2880-4fb2-11e9-82d0-e63cea6655ba.gif)

I checked Sweetalert2 issues, and they advise that you must import the _js_ file instead of from barrel file, but in _ngx-sweetalert2_ I don't know if we can do that (reference: https://github.com/sweetalert2/sweetalert2/issues/1137#issuecomment-400239982).

Thanks!.

**Comment by toverux** [comment] 2019-03-27 22:35
If you import the JS file only with bunded styles, you can't customize the SCSS variables. You have to include your SCSS file yourself in order to do that. Are you sure you've imported the right file? I admit that I've never tested overriding SweetAlert's SCSS variables myself, I should try that and document it at some point.
In the meanwhile, if you're stuck, you can still override the styles with pure CSS.

**Comment by limonte** [comment] 2019-04-29 11:14
I don't think it's possible to use/override SASS variables with `ngx-sweetalert2`.

In sources there are

```js
import Swal from 'sweetalert2' 
```

which means

```js
import Swal from 'sweetalert2/dist/sweetalert2.all.js' 
```

which means that default styles will be injected automatically.

**Comment by steve3d** [comment] 2019-08-07 02:42
well, this is a very important problem for angular, becuase injected styles are inserted last, there is no way to override the styles, unless we add `!important` to every rule of override.

and this by sweetalert2's default design, sweetalert2 will use dist/sweetalert2.all.js, the only way to change this is by change `"browser": "dist/sweetalert2.all.js"`  to `"browser": "dist/sweetalert2.js"`  in `node_modules/sweetalert2/package.json`

**Comment by toverux** [comment] 2019-08-07 08:13
Actually, it is also possible to override this in your webpack configuration... the problem is that todays Angular CLI hides the webpack config behind angular.json. You can have a custom setup that lets you modify it, but I'll not document that here.

And yes indeed, this was a very conscious choice. Back in the days, sweetalert2 did not inject styles by default, and we were regularly getting issues with people forgetting to include the SCSS/CSS, despite it was documented. This ceased since we produced a JS build embedding the styles. 

If I can find time and motivation to release a new version of ngx-sweetalert2 soonish, I will address this problem by letting you pass the sweetalert2 module yourself in the module configuration, so you'll be able to pass the unstyled JavaScript instead and use the SCSS sources.

**Comment by steve3d** [comment] 2019-08-09 13:18
well, for now I'm using a very ugly hack, which is patch the `browser` content of package.json to do this.

**Comment by toverux** [comment] 2019-09-03 19:08
Hello! Good news! [v6.0.0](https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v6.0.0) is out and allows you to load an arbitrary build of SweetAlert2, here we're interested in the unstyled one.

To use a theme, import SweetAlert2 like this:

```ts
import { SweetAlert2Module } from '@sweetalert2/ngx-sweetalert2';

// the function must be outside of @NgModule and exported or the AoT compiler complains
export function provideSwal() {
    return import('sweetalert2/src/sweetalert2.js'); // instead of import('sweetalert2')
}

@NgModule({
    imports: [
        SweetAlert2Module.forRoot({ provideSwal })
    ]
})
export class AppModule {
}
```

Here I'm importing SweetAlert2 directly from the original source. If you want to be safer you may want to choose to import from `sweetalert2/dist/sweetalert2.js` instead.

Then, import the theme you prefer, for example, in SASS:

```scss
@import '~@sweetalert2/themes/borderless/borderless';
```

Or in your `angular.json`:

```js
"styles": [
      "node_modules/@sweetalert2/themes/borderless/borderless.css" // or .scss if you have SASS enabled
],
```

**Closed** 2019-09-03 19:10 UTC

**Comment by toverux** [comment] 2020-12-27 20:53
New wiki page on this subject! https://github.com/sweetalert2/ngx-sweetalert2/wiki/Use-a-theme-from-@sweetalert2-themes-(and-or-customize-SCSS-variables)
