### ISSUE TITLE
Error with Angular 8 and ngx-sweetalert2@7.30

### ISSUE THREAD

**Issue by AlmudenaBarrero** [sweetalert2/ngx-sweetalert2#160] opened 2020-04-30 08:21 UTC
I have this error when I try to run ng serve:

![image](https://user-images.githubusercontent.com/49492653/80688186-b6e9ef00-8acb-11ea-920b-75ecd2b2fbe8.png)

I have this versions:

- Angular 8.3.25
- @sweetalert2/ngx-sweetalert2 ~7.3.0
- sweetalert2 9.10.12

How can I do for make it works?

Thank you!

**Comment by toverux** [comment] 2020-04-30 11:49
Do you use a custom Webpack setup ?

**Comment by AlmudenaBarrero** [comment] 2020-04-30 12:37
No, I haven't got custom webpack setup

**Comment by AlmudenaBarrero** [comment] 2020-05-05 07:43
Any news with that? I still has the error.
Thank you

**Comment by limonte** [comment] 2020-05-06 11:12
you might find the solution here https://github.com/babel/babel-loader/issues/493

closing because the issue is not related to the library itself.

**Closed by limonte** 2020-05-06 11:12 UTC

**Comment by AlmudenaBarrero** [comment] 2020-05-11 10:20
I'm not using babel-loader in my project. If I need that to make it works maybe you should add this info to your README!
I still have this error...
