### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by manishaquil** [sweetalert2/ngx-sweetalert2#230] opened 2022-12-10 05:12 UTC
When added in package json and build processing showing this message.

/node_modules/@sweetalert2/ngx-sweetalert2/fesm2020/sweetalert2-ngx-sweetalert2.mjs depends on 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by limonte** [comment] 2022-12-12 07:58
duplicate of https://github.com/sweetalert2/sweetalert2/issues/2467

**Closed by limonte** 2022-12-12 07:58 UTC

**Comment by toverux** [comment] 2022-12-12 09:33
You can use provideSwal to change the import (as shown by @limonte): https://github.com/sweetalert2/ngx-sweetalert2/wiki/Setting-global-defaults-(SweetAlert2-mixins)
Then you'll have to import the SwetAlert SCSS or CSS separately, in your styles.[s]css or angular.json.

**Comment by iGanja** [comment] 2023-02-10 20:39
Just thought I'd point out, - from another thread where this is mentioned - the error message also provides a link "For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies" which pretty much explains how to silence this warning. There is no way to eliminate the risk, which is not significant, IMHO. The issue that CommonJS can increase your bundle size is certainly true, but if you are happy with the size of your package, yada yada, pun intended.
